from pipig import app
from pipig.gpio_pins.models import GpioPin

def data_setup():
    with app.app_context():
        GpioPin.create(pin_position=1, pin_number=None, bcm_pin=None, pin_name="3v3 Power")
        GpioPin.create(pin_position=2, pin_number=None, bcm_pin=None, pin_name="5V Power")
        GpioPin.create(pin_position=3, pin_number=3, bcm_pin=2, pin_name="SDA")
        GpioPin.create(pin_position=4, pin_number=None, bcm_pin=None, pin_name="5V Power")
        GpioPin.create(pin_position=5, pin_number=5, bcm_pin=3, pin_name="SCL")
        GpioPin.create(pin_position=6, pin_number=None, bcm_pin=None, pin_name="Ground")
        GpioPin.create(pin_position=7, pin_number=7, bcm_pin=4, pin_name="GPCLK0")
        GpioPin.create(pin_position=8, pin_number=8, bcm_pin=14, pin_name="TXD")
        GpioPin.create(pin_position=9, pin_number=None, bcm_pin=None, pin_name="Ground")
        GpioPin.create(pin_position=10, pin_number=10, bcm_pin=15, pin_name="RXD")
        GpioPin.create(pin_position=11, pin_number=11, bcm_pin=17, pin_name="")
        GpioPin.create(pin_position=12, pin_number=12, bcm_pin=18, pin_name="PWM0")
        GpioPin.create(pin_position=13, pin_number=13, bcm_pin=27, pin_name="")
        GpioPin.create(pin_position=14, pin_number=None, bcm_pin=None, pin_name="Ground")
        GpioPin.create(pin_position=15, pin_number=15, bcm_pin=22, pin_name="")
        GpioPin.create(pin_position=16, pin_number=16, bcm_pin=23, pin_name="")
        GpioPin.create(pin_position=17, pin_number=None, bcm_pin=None, pin_name="3v3 Power")
        GpioPin.create(pin_position=18, pin_number=18, bcm_pin=24, pin_name="")
        GpioPin.create(pin_position=19, pin_number=19, bcm_pin=10, pin_name="MOSI")
        GpioPin.create(pin_position=20, pin_number=None, bcm_pin=None, pin_name="Ground")
        GpioPin.create(pin_position=21, pin_number=21, bcm_pin=9, pin_name="MISO")
        GpioPin.create(pin_position=22, pin_number=22, bcm_pin=25, pin_name="")
        GpioPin.create(pin_position=23, pin_number=23, bcm_pin=11, pin_name="SCLK")
        GpioPin.create(pin_position=24, pin_number=24, bcm_pin=8, pin_name="CEO")
        GpioPin.create(pin_position=25, pin_number=None, bcm_pin=None, pin_name="Ground")
        GpioPin.create(pin_position=26, pin_number=26, bcm_pin=7, pin_name="CE1")
        GpioPin.create(pin_position=27, pin_number=27, bcm_pin=0, pin_name="IS_SD")
        GpioPin.create(pin_position=28, pin_number=28, bcm_pin=1, pin_name="ID_SC")
        GpioPin.create(pin_position=29, pin_number=29, bcm_pin=5, pin_name="")
        GpioPin.create(pin_position=30, pin_number=None, bcm_pin=None, pin_name="Ground")
        GpioPin.create(pin_position=31, pin_number=31, bcm_pin=6, pin_name="")
        GpioPin.create(pin_position=32, pin_number=32, bcm_pin=12, pin_name="PWM0")
        GpioPin.create(pin_position=33, pin_number=33, bcm_pin=13, pin_name="PWM1")
        GpioPin.create(pin_position=34, pin_number=None, bcm_pin=None, pin_name="Ground")
        GpioPin.create(pin_position=35, pin_number=35, bcm_pin=19, pin_name="MISO")
        GpioPin.create(pin_position=36, pin_number=36, bcm_pin=16, pin_name="")
        GpioPin.create(pin_position=37, pin_number=37, bcm_pin=26, pin_name="")
        GpioPin.create(pin_position=38, pin_number=38, bcm_pin=20, pin_name="MOSI")
        GpioPin.create(pin_position=39, pin_number=None, bcm_pin=None, pin_name="Ground")
        GpioPin.create(pin_position=40, pin_number=40, bcm_pin=21, pin_name="SCLK")

if __name__ == '__main__':
    # with app.app_context():
    data_setup()
